---
title: "Clustering"
author: "Шавронская Дарья Олеговна"
date: "2022-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

подгрузим библиотеки 

```{r}
library(factoextra)
library(dplyr)
library(skimr)
library(pheatmap)
library(purrr)
```
считаем данные из txt

```{r}
clinical_p <- read.delim2("data_clinical_patient.txt")
colnames(clinical_p) <- clinical_p[4,] 
clinical_p <- slice(clinical_p , -c(1:4))
clinical_p

clinical_s <-read.delim("data_clinical_sample.txt")
colnames(clinical_s) <- clinical_s[4,] 
clinical_s <- slice(clinical_s, -c(1:4))
clinical_s

mrna <-read.delim("data_mrna_seq_v2_rsem.txt") %>%
  select(- Hugo_Symbol)
mrna

```
объдиним клинические данные
```{r}
clinical <- clinical_p %>%
  full_join(clinical_s, by = c("PATIENT_ID"="PATIENT_ID"))
str(clinical)

clinical %>%
  map(table, useNA = "always")
```

логарифмируем данные 
```{r}
mrna_log2 <- log(mrna[-1]+ 1, base = 2)
mrna_log2_full <- cbind(mrna[1],mrna_log2)
dim(mrna_log2_full)


```
отфильтруем наиболее экспрессируемые гены
```{r}
keep <- rowSums(mrna_log2_full > 12) > 444/10
mrna_log2_filtered <- df3_log2_full[keep, ]
mrna_log2_filtered 
```


проведем кластеризацию
```{r}
mrna_log2_filtered_scaled <- scale(mrna_log2_filtered)
mrna_log2_filtered_scaled_dist <- dist(mrna_log2_filtered_scaled, method = "euclidean")
hc_mrna <- hclust(mrna_log2_filtered_scaled_dist, 
                        method = "ward.D2")
fviz_dend(hc_mrna, 
          cex = 0.5)
```
модифицируем данные

```{r}
modified_sd = function(x){
  return((x-mean(x))/sd(x))
}
mrna_log2_sd <-apply(mrna_log2, 2, modified_sd)

mrna_log2_sd_full <- cbind(mrna_log2_full[1],mrna_log2_sd)
mrna_log2_sd_full
```
отфильтруем данные

```{r}
keep2 <- rowSums(mrna_log2_sd_full > 1.5) > 444/10
mrna_log2_filtered_sd <- mrna_log2_sd_full[keep2, ]
mrna_log2_filtered_sd 
```
проведем кластеризацию и построим дендрограмму
```{r}
mrna_log2_filtered_sd_scaled <- scale(mrna_log2_filtered_sd)
mrna_log2_filtered_sd_scaled_dist <- dist(mrna_log2_filtered_sd_scaled, method = "euclidean")
hc_rmna_sd <- hclust(d = mrna_log2_filtered_sd_scaled_dist, 
                       method = "ward.D2")
fviz_dend(hc_rmna_sd, 
        cex = 0.5)
```

модифицируем данные
```{r}
modified_mad = function(x){
  return((x - median(x))/mad(x))
}
mrna_log2_mad <-apply(mrna_log2, 2, modified_mad)

mrna_log2_mad_full <- cbind(mrna_log2_full[1],mrna_log2_mad)
mrna_log2_mad_full
```
отфильтруем данные
```{r}
keep3 <- rowSums(mrna_log2_mad_full > 1) > 444/10
mrna_log2_filtered_sd <- mrna_log2_sd_full[keep3, ]
mrna_log2_filtered_sd 
```

проведем кластеризацию и построим дендрограмму

```{r}
mrna_log2_filtered_sd_scaled <- scale(mrna_log2_filtered_sd)
mrna_log2_filtered_sd_scaled_dist <- dist(mrna_log2_filtered_sd_scaled, method = "euclidean")
hc_mrna_mad <- hclust(mrna_log2_filtered_sd_scaled_dist, 
                    method = "ward.D2")
fviz_dend(hc_mrna_mad, 
          cex = 0.5)
```

