---
title: "TCGA_SKCM_Report_DZ_2"
author: "Dmitry Zubkov"
date: "December 14, 2022"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(factoextra)
library(ggbiplot)
library(ComplexHeatmap)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


## Transcriptomics data

```{r transcriptomics}

df.t <- 
  read_tsv("../raw/data_mrna_seq_v2_rsem.txt") %>%
  select(-Hugo_Symbol) %>%
  distinct(Entrez_Gene_Id, .keep_all = TRUE)

zeros <- apply(as.matrix(df.t[-1]), 1, function(x) all(x == 0))

df.t <- df.t[!zeros, ]

```

```{r transformation}

mat.raw <- t(df.t[-1])
colnames(mat.raw) <- df.t$Entrez_Gene_Id
rownames(mat.raw) <- colnames(df.t)[-1]

imp_zeros <- function(x) {
  x[x == 0] <- NA
  x[is.na(x)] <- min(x, na.rm = T)/2
  return(x)
}

mat.log <- log2(apply(mat.raw, 2, imp_zeros))
  
#mat.log <- log2(mat.raw + 1)

```

### Log2 (imputed values), median centered, no scaling

```{r heatmap_1}
features <- 
  apply(mat.log, 2, mad) %>%
  sort(decreasing = T) %>%
  .[1:1500] %>%
  names()

mat.scaled <- apply(mat.log, 2, function(x) x - median(x))

mat <- mat.scaled[, features]

Heatmap(mat, show_row_names = F, show_column_names = F,
        row_title = "Samples", column_title = "Genes",
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "average",
        clustering_distance_columns = "euclidean",
        clustering_method_columns = "average")
```

### Log2 (imputed values), median centered, mad scaled

```{r heatmap_2}
features <- 
  apply(mat.log, 2, mad) %>%
  sort(decreasing = T) %>%
  .[1:1500] %>%
  names()

mat.scaled <- apply(mat.log, 2, function(x) (x - median(x))/mad(x))

mat <- mat.scaled[, features]

Heatmap(mat, show_row_names = F, show_column_names = F,
        row_title = "Samples", column_title = "Genes",
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "average",
        clustering_distance_columns = "euclidean",
        clustering_method_columns = "average")

```

### Log2 (imputed values), mean centered, no scaling

```{r heatmap_3}

features <- 
  apply(mat.log, 2, sd) %>%
  sort(decreasing = T) %>%
  .[1:1500] %>%
  names()

mat.scaled <- apply(mat.log, 2, function(x) x - mean(x))

mat <- mat.scaled[, features]

Heatmap(mat, show_row_names = F, show_column_names = F,
        row_title = "Samples", column_title = "Genes",
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "average",
        clustering_distance_columns = "euclidean",
        clustering_method_columns = "average")

```

### Log2 (imputed values), mean centered, sd scaled

```{r heatmap_4}
features <- 
  apply(mat.log, 2, sd) %>%
  sort(decreasing = T) %>%
  .[1:1500] %>%
  names()

mat.scaled <- apply(mat.log, 2, function(x) (x - mean(x))/sd(x))

mat <- mat.scaled[, features]

Heatmap(mat, show_row_names = F, show_column_names = F,
        row_title = "Samples", column_title = "Genes",
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "average",
        clustering_distance_columns = "euclidean",
        clustering_method_columns = "average")

pca <- prcomp(mat, center = F, scale = F, rank = 10)
fviz_pca_ind(pca, geom.ind = "point")
fviz_pca_var(pca, geom.var = "point")

ck.bp <- clusterProfiler::compareCluster(geneCluster = list("1500 genes" = colnames(mat)),
                                         fun = "enrichGO", OrgDb = "org.Hs.eg.db", ont = "BP",
                                         pvalueCutoff = 0.01, qvalueCutoff =  0.01)


clusterProfiler::dotplot(ck.bp, by = "count", showCategory = 20, 
                         title = "Gene Ontology enrichment") + 
  scale_colour_gradient(limits=c(0, 0.001), low="red", high="blue") +
  theme(plot.title = element_text(hjust = 0.5))


```

```{r clust, eval = FALSE}

hc <-
  mat %>%
  #scale() %>%
  dist(method = "euclidean") %>%
  hclust(method = "average")

```

```{r clust_plot, eval = FALSE}

grp <- cutree(hc, k = 2)

fviz_cluster(list(data = mat, cluster = grp),
             palette = "Set1",
             ellipse.type = "convex",
             show.clust.cent = FALSE,
             labelsize = 0,
             ggtheme = theme_minimal())
```
